project:
  type: book

book:
  title: "R Training Book for IKU"
  chapters:
    - index.qmd
    - './01_HowToUseThisBook/01_HowToUseThisBook.qmd'
    - './02_Introduction/02_Introduction.qmd'
    - './03_DataWrangling/03_DataWrangling.qmd'
    - './04_DataVizualization/04_DataVizualization.qmd'
    - './05_BasicStatisticalAnalysis/05_BasicStatisticalAnalysis.qmd'
    - './06_ComplexSamplingDesign/06_ComplexSamplingDesign.qmd'

format:
  pdf:
    documentclass: scrbook
    pdf-engine: xelatex
    include-in-header:
      text: |
        \usepackage{typearea}
        \usepackage{fontspec}
        \usepackage{microtype}
        \usepackage{indentfirst}
        \usepackage{xcolor}
        \usepackage{multicol}
        \usepackage{listings}
        \usepackage{hyperref}
        \usepackage{url}
        \hypersetup{
          breaklinks=true,
          colorlinks=true,
          linkcolor=blue,
          urlcolor=blue
        }
        \urlstyle{same}
        \lstset{
          basicstyle=\ttfamily,
          breaklines=true,
          breakatwhitespace=false,
          postbreak=\mbox{\textcolor{red}{$\hookrightarrow$}\space}
        }
        \setlength{\parindent}{1.5em}
        \sloppy
        \hyphenpenalty=10000
        \exhyphenpenalty=10000
        \newcommand{\highlighttext}[1]{\colorbox{gray!30}{\textcolor{purple}{#1}}}
    papersize: a4
    geometry:
      - top=30mm
      - bottom=35mm
      - right=25mm
      - left=25mm
      - heightrounded
      - bindingoffset=10mm
    mainfont: Rasa
    mainfontoptions:
      - Path=./font/Rasa/
      - Extension=.ttf
      - UprightFont=*-Regular
      - ItalicFont =*-Italic
      - BoldFont=*-Bold
      - BoldItalicFont=*-BoldItalic
    monofont: FiraCode
    monofontoptions:
      - Path=./font/FiraCode/
      - Extension=.ttf
      - UprightFont=*-Regular
      - Contextuals=Alternate
    code-line-numbers: true
    code-block-bg: '#fdf6e3'

execute:
  warning: false
