project:
  type: book

book:
  title: "IKU_RBook"
  author: "Mohd Azmi Bin Suliman"
  date: last-modified
  date-format: "dddd, DD/MM/YYYY"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd
bibliography: references.bib

format:
  pdf:
    documentclass: scrreprt
    monofont: 'Fira Code'
    mainfont: Roboto
  html:
    theme: sandstone
    code-fold: show
    code-overflow: wrap
    code-tools: true
    df-print: paged
    embed-resources: true
    monofont: 'Fira Code'



